# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-13 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0006_event_sentinel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_by',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], default='EMAIL', max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='log_type',
            field=models.CharField(choices=[('LOG', 'Log'), ('NOT', 'Notification')], default='LOG', max_length=3),
        ),
    ]
