#!/Users/dane/env/w4e/bin/python
import os
import django
from django.conf import settings
import requests
import json
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from sentinel.models import Event, Sentinel
from django.contrib.auth.models import User


def summary():
    u = Event.objects.count()
    p = Sentinel.objects.count()
    message = 'There are %d events and %d sentinels' % (u, p)
    print(message)

if __name__ == '__main__':
    summary()
